# 활성화 설정
enable:
  issues: false
  prs: true

# 레이블 적용 시 코멘트
comments:
  prs: |
    Labeler has automatically applied labels based on your PR title or description.
    Please check that they are appropriate.

# 라벨 매칭 규칙
labels:
  'feature':
    include:
      - '\bfeat\b'
      - '\bfeature\b'

  'bug':
    include:
      - '\bfix\b'
      - '\bbug\b'

  'refactor':
    include:
      - '\brefactor\b'

  'docs':
    include:
      - '\bdocs\b'
      - '\breadme\b'

  'test':
    include:
      - '\btest\b'

  'chore':
    include:
      - '\bchore\b'
      - '\bconfig\b'
