# ============================================
# 🏷️ 자동 라벨링 규칙 (AF-FE Git Flow 반영)
# ============================================

feat:
  - head-branch:
      - '^feat/'
      - '^feature/'
  - paths:
      - 'src/pages/**'
      - 'src/auth/**'
      - 'src/stamp/**'
      - 'src/shared/components/**'
      - 'src/shared/styles/**'

setting:
  - head-branch:
      - '^setting/'
  - paths:
      - 'config/**'
      - '.env*'
      - 'package.json'
      - 'tailwind.config.js'
      - 'next.config.ts'
      - 'tsconfig.json'
      - 'postcss.config.mjs'
      - 'eslint.config.mjs'

api:
  - head-branch:
      - '^api/'
  - paths:
      - 'src/shared/api/**'
      - 'src/shared/hooks/**'
      - 'src/shared/utils/**'

fix:
  - head-branch:
      - '^fix/'
  - title:
      - '\[Fix\]'
  - paths:
      - 'src/**'

release:
  - head-branch:
      - '^release/'
  - paths:
      - 'CHANGELOG.md'

hotfix:
  - head-branch:
      - '^hotfix/'
      - '^HOTFIX/'
  - title:
      - '\[Hotfix\]'
  - paths:
      - 'src/**'

docs:
  - paths:
      - '**/*.md'
      - 'README.md'

refactor:
  - head-branch:
      - '^refactor/'
  - title:
      - '\[Refactor\]'
  - paths:
      - 'src/**'
