labels:
  - label: "feat"
    head-branch:
      - "^feat/"
      - "^feature/"
    paths:
      - "src/pages/**"
      - "src/auth/**"
      - "src/stamp/**"
      - "src/shared/components/**"
      - "src/shared/styles/**"

  - label: "setting"
    head-branch:
      - "^setting/"
    paths:
      - "config/**"
      - ".env*"
      - "package.json"
      - "tailwind.config.js"
      - "next.config.ts"
      - "tsconfig.json"
      - "postcss.config.mjs"
      - "eslint.config.mjs"

  - label: "api"
    head-branch:
      - "^api/"
    paths:
      - "src/shared/api/**"
      - "src/shared/hooks/**"
      - "src/shared/utils/**"

  - label: "fix"
    head-branch:
      - "^fix/"
    title:
      - "\\[Fix\\]"
    paths:
      - "src/**"

  - label: "release"
    head-branch:
      - "^release/"
    paths:
      - "CHANGELOG.md"

  - label: "hotfix"
    head-branch:
      - "^hotfix/"
      - "^HOTFIX/"
    title:
      - "\\[Hotfix\\]"
    paths:
      - "src/**"

  - label: "docs"
    paths:
      - "**/*.md"
      - "README.md"

  - label: "refactor"
    head-branch:
      - "^refactor/"
    title:
      - "\\[Refactor\\]"
    paths:
      - "src/**"

