name: Auto Assign Reviewer & Assignee

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers and assignee
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # PR 작성자 자동 지정
          reviewers: skyblue1232, jjangminii, KongMezu # GitHub username 기준
