name: PR Labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Apply labels automatically
        uses: jimschubert/labeler-action@v1
        with:
          configuration-path: .github/pr-labeler-config.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
